version: "3.9"
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: shop
    ports: ["5432:5432"]

  redis:
    image: redis:8
    ports: ["6379:6379"]

  monolith-api:
    build: ./monolith-api
    depends_on: [postgres, redis]
    ports: ["4000:4000"]
    volumes:
      - ./monolith-api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  web-client:
    build: ./web-client
    depends_on: [monolith-api]
    ports: ["3000:3000"]
    volumes:
      - ./web-client:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development